name: Pipeline CD

on:
  workflow_run:
    workflows: ["Pipeline CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploiement sur Render
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.APITOKEN_READ_WRITE }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "${{ secrets.SERVICEID }}", "deployHook": "manual"}' \
          https://api.render.com/v1/services/${{ secrets.SERVICEID }}/deploys