name: Pipeline CD

on:
  workflow_run:
    workflows: ["Pipeline CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer code
      uses: actions/checkout@v3

    - name: Configurer Docker
      run: |
        echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.DEVOPSNAME }}" --password-stdin

    - name: Construire et pousser image Docker
      run: |
        docker build -t ${{ secrets.DEVOPSNAME }}/rest-api-java:latest .
        docker push ${{ secrets.DEVOPSNAME }}/rest-api-java:latest

    - name: Deploiement sur Render
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.APIKEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "${{ secrets.SERVICEID }}", "deployHook": "manual"}' \
          https://api.render.com/v1/services/${{ secrets.SERVICEID }}/deploys