name: Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compiler-et-tester:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer code
      uses: actions/checkout@v3

    - name: Configurer Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compiler code Java
      run: |
        cd src
        javac *.java

    - name: Construire image Docker
      run: |
        docker build -t rest-api-java .

    - name: Lancer conteneur et tester API
      run: |
        docker run -d -p 8080:8080 --name rest-api-java-container rest-api-java
        sleep 10 # Attendre que le conteneur demarre
        docker ps | grep rest-api-java-container # Verifier que le conteneur est en cours
        curl -X POST http://localhost:8080/tickets -d "ticket=001" | grep "Ticket ajoute : 001" || exit 1
        curl http://localhost:8080/tickets/count | grep "Personnes en attente : 1" || exit 1
        curl http://localhost:8080/tickets/peek | grep "Prochain ticket : 001" || exit 1
        curl http://localhost:8080/tickets/next | grep "Ticket traite : 001" || exit 1
        curl http://localhost:8080/tickets/next | grep "Erreur : File vide" || exit 1
        curl -X PUT http://localhost:8080/tickets | grep "Methode ou chemin non autorise" || exit 1
        docker stop rest-api-java-container # Arreter le conteneur