name: Pipeline CD

on:
  push:
    branches:
      - main

jobs:
  deployer:
    runs-on: ubuntu-latest
    steps:
    - name: Recuperer code
      uses: actions/checkout@v3

    - name: Configurer Docker
      uses: docker/setup-buildx-action@v2

    - name: Connexion a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DEVOPSNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Construire et pousser image Docker
      run: |
        docker build -t ${DEVOPSNAME}/rest-api-java:latest .
        docker push ${DEVOPSNAME}/rest-api-java:latest

    - name: Deploiement sur Render
      env:
        RENDER_API_TOKEN: ${{ secrets.APIKEY }}
        RENDER_SERVICE_ID: ${{ secrets.SERVICEID }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $APIKEY" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "'$SERVICEID'"}' \
          https://api.render.com/v1/services/$SERVICEID/deploys